djangoProject1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page, get_email
from djangoProject1.views import header, footer, about_page
from django.conf import settings

# from e_shop import settings

urlpatterns = [
    path('', home_page),
    path('admin/', admin.site.urls),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('about-us', about_page),
    path('get-email', get_email),
    path('', include("eshop_account.urls")),
    path('', include("eshop_product.urls")),
    path('', include("eshop_order.urls")),
    path('', include("eshop_contact.urls")),
    path('', include("eshop_wish_list.urls")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_order/urls.py
from django.urls import path
from eshop_order.views import add_user_order, user_open_order,add_user_order_single, send_request, verify , delete_order_detail

urlpatterns = [
    path('add_user_order', add_user_order),
    path('add_user_order/<productId>', add_user_order_single),
    path('open-order', user_open_order),
    path('delete_order_detail/<detail_id>', delete_order_detail),
    path('request', send_request, name='request'),
    path('verify/<order_id>', verify, name='verify'),
]

eshop_product/urls.py
from django.urls import path
from .views import ProductsList, product_detail, SearchProductsView, ProductsListByCategory , ProductsListByOrder, products_categories_partial

urlpatterns = [
    path('products', ProductsList.as_view()),
    path('products/orderby/<order>', ProductsListByOrder.as_view()),
    path('products/list/<category_name>', ProductsListByCategory.as_view()),
    path('products/<productId>/<name>', product_detail),
    path('products/search', SearchProductsView.as_view()),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial')
]

eshop_product/models.py
from django.db.models import Q
from django.db import models
import os

from eshop_product_category.models import ProductCategory


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/{final_name}"


def upload_gallery_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/galleries/{final_name}"


class ProductsManager(models.Manager):
    def get_active_products(self):
        return self.get_queryset().filter(active=True)
    def get_by_order(self,given_order):
        return self.get_queryset().order_by(given_order)

    def get_products_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def search(self, query):
        lookup = (
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(tag__title__icontains=query)
        )
        return self.get_queryset().filter(lookup, active=True).distinct()


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    price = models.IntegerField(verbose_name='قیمت')
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True, verbose_name='تصویر')
    active = models.BooleanField(default=False, verbose_name='فعال / غیرفعال')
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name="دسته بندی ها")
    existing = models.BooleanField(default=True, verbose_name="موجود")
    visit_count = models.IntegerField(default=0 , verbose_name="تعداد بازدید")

    objects = ProductsManager()

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/products/{self.id}/{self.title.replace(' ', '-')}"


class ProductGallery(models.Model):
    title = models.CharField(max_length=150, verbose_name="عنوان")
    image = models.ImageField(upload_to=upload_image_path, verbose_name='تصویر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'تصاویر'

    def __str__(self):
        return self.title

eshop_product/views.py
import itertools
import datetime
from django.shortcuts import render
from django.views.generic import ListView

from eshop_order.forms import UserNewOrderForm
from .models import Product, ProductGallery
from django.http import Http404
from eshop_product_category.models import ProductCategory

from eshop_settings.models import SocialMedia


# Create your views here.

class ProductsList(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.get_active_products()

class ProductsListByOrder(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.get_by_order(self.kwargs['order'])


class ProductsListByCategory(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        category = ProductCategory.objects.filter(name__iexact=category_name).first()
        if category is None:
            raise Http404('صفحه ی مورد نظر یافت نشد')
        return Product.objects.get_products_by_category(category_name)


def my_grouper(n, iterable):
    args = [iter(iterable)] * n
    return ([e for e in t if e is not None] for t in itertools.zip_longest(*args))


def my_grouper2(iterable, num):
    y = [iterable[n:n + num] for n in range(len(iterable) - (num - 1))]
    return y


def product_detail(request, *args, **kwargs):
    selected_product_id = kwargs['productId']
    new_order_form = UserNewOrderForm(request.POST or None, initial={"product_id": selected_product_id})
    product: Product = Product.objects.get_by_id(selected_product_id)
    social_media = SocialMedia.objects.all()

    if product is None or not product.active:
        raise Http404('محصول مورد نظر یافت نشد')

    product.visit_count += 1
    product.save()
    related_products = Product.objects.get_queryset().filter(categories__product=product).distinct()

    grouped_related_products = my_grouper(3, related_products)

    context = {
        'product': product,
        'related_products': grouped_related_products,
        "new_order_form": new_order_form,
        "date": datetime.datetime.now().date,
        "social_media": social_media
    }

    return render(request, 'products/product_detail.html', context)


class SearchProductsView(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6
    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Product.objects.search(query)

        return Product.objects.get_active_products()


def products_categories_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'products/products_categories_partial.html', context)

eshop_product/templates/products/product_detail.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}
    <section>
        <div class="container">

            <div class="row">
                <div class="col-sm-9 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product.image.url }}" alt="" style="width: 100%; height: 100%">

                            </div>


                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->

                                <div>
                                    <h2>{{ product.title }}</h2>
                                    <p>شناسـه : {{ product.id }}</p>
                                </div>
                                <div>
									<span>
										<span>قیمت : {{ product.price }} تومان </span>
									</span>
                                    <span>
                                        <form method="post" action="/add_user_order">
                                            {% csrf_token %}
                                            {{ new_order_form.product_id }}
                                            <label>تعداد :</label>
                                            {{ new_order_form.count }}
										<button type="submit" class="btn btn-fefault cart">
											<i class="fa fa-shopping-cart"></i>
											افـزودن به سبـد خریـد
										</button>
                                        </form>

									</span>
                                </div>
                                <div>
                                    <p><b>موجـودی :</b> در انبـار موجود می باشد</p>
                                    <p><b>شرایـط :</b> جدیـد</p>
                                    <p><b>برنـد :</b> برنـد </p>
                                </div>
                                <span class="socials-share share">
									<ul>
                                        {% for s in social_media %}
                                            <a href="{{ s.social_link }}">
											<li>
												<img style="width:10%;height: 10%;" src="{{ s.social_image.url }}">
                                                <label>{{ s.social_name }}</label>
											</li>
										</a>
                                        {% endfor %}
									</ul>
								</span>

                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#details" data-toggle="tab">جزئیات</a></li>

                                <li><a href="#tag" data-toggle="tab">برچسب</a></li>
{#                                <li class=""><a href="#reviews" data-toggle="tab">نظرات (5)</a></li>#}
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="details">
                                <div class="col-md-12">
                                    <p>
                                        {{ product.description }}
                                    </p>
                                </div>
                            </div>

                            <div class="tab-pane fade" id="tag">
                                {% for category in product.categories.all %}
                                    <button class="button"><a
                                            href="/products/{{ category.name }}">{{ category.title }}</a>
                                    </button>
                                {% endfor %}
                            </div>

{#                            <div class="tab-pane fade" id="reviews">#}
{#                                <div class="col-sm-12">#}
{#                                    <ul>#}
{#                                        <li><a href=""><i class="fa fa-user"></i>{{ request.user.username }}</a></li>#}
{#                                        <li><a href=""><i class="fa fa-calendar-o"></i>{{ date }}</a></li>#}
{#                                    </ul>#}
{#                                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده ازلورملورم#}
{#                                        ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان#}
{#                                        گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و#}
{#                                        برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای#}
{#                                        کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان#}
{#                                        جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه#}
{#                                        ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p>#}
{#                                    <p><b>نظـر خود را بنویسیـد</b></p>#}
{##}
{#                                    <form action="#">#}
{#										<span>#}
{#											<input type="text" placeholder="نام و نام خانوادگـی">#}
{#											<input type="email" placeholder="آدرس ایمیـل">#}
{#										</span>#}
{#                                        <textarea name=""></textarea>#}
{#                                        <b>رتبـه : </b> <img src="{% static 'images/product-details/rating.png' %}"#}
{#                                                             alt="">#}
{#                                        <button type="button" class="btn btn-default pull-left">#}
{#                                            ارسـال#}
{#                                        </button>#}
{#                                    </form>#}
{#                                </div>#}
{#                            </div>#}

                        </div>
                    </div><!--/category-tab-->

                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">محصولات پیشنهادی</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product_list in related_products %}
                                    <div class="item {% if forloop.first %} active {% endif %}">
                                        {% for product in product_list %}
                                            {% include "products/product_item_component.html" with product=product %}
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel"
                               data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel"
                               data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--/recommended_items-->

                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'products_categories_partial' %}
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

eshop_product/templates/products/product_item_component.html
<div class="col-sm-4 pull-right">
    <a href="/products/{{ product.id }}/{{ product.title }}">

        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="{{ product.image.url }}" alt="">
                    <h2>{{ product.price }} تومان</h2>
                    <p>{{ product.title }}</p>
                    <a href="/add_user_order/{{ product.id }}" class="btn btn-default add-to-cart"><i
                            class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>
                </div>
                <div class="product-overlay">
                    <a href="/products/{{ product.id }}/{{ product.title }}">
                        <div class="overlay-content">
                            <h2>{{ product.price }} تومان</h2>
                            <p>{{ product.title }}</p>
                            <a href="/add_user_order/{{ product.id }}" class="btn btn-default add-to-cart"><i
                                    class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>

                        </div>
                    </a>

                </div>
            </div>

        </div>
    </a>
</div>

eshop_product/templates/products/products_categories_partial.html
<h2>دسته بندی محصولات</h2>
<div class="panel-group category-products" id="accordian">
    <div class="panel panel-default">
            <div class="mainmenu">
                <ul>
                    <li><a href="/products">همه</a></li>
                    <hr>
                    {% for category in categories %}
                        <li><a
                                href="/products/list/{{ category.name }}">{{ category.title }}</a>
                        </li>
                        <br>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

eshop_product/templates/products/products_list.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}
    <section>
        <div class="container">
            <div class="mainmenu pull-right">
                <ul class="nav navbar-nav collapse navbar-collapse ">
                    <li class="dropdown"><a href="#">ترتیب<i class="fa fa-angle-down"></i></a>
                        <ul role="menu" class="sub-menu">
                            <li><a href="/products/orderby/price">قیمت (کم ترین)</a></li>
                            <li><a href="/products/orderby/-price">قیمت (بیش ترین)</a></li>
                            <li><a href="/products/orderby/title">اسم</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="row">
                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->

                        <h2 class="title text-center">لیست محصولات</h2>
                        {% for product in page_obj %}
                            {% include 'products/product_item_component.html' with product=product %}
                        {% endfor %}


                        <div class="clearfix"></div>
                        <ul class="pagination">

                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div><!--features_items-->
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'products_categories_partial' %}
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}